version: "3.3"
services:
  eureka:
    image: epitech/eureka:latest
    environment:
      - BLA=bla
    ports:
      - ${porteureka}:8761
    deploy:
      resources:
        limits:
          memory: 200MB
  gateway:
    image: epitech/gateway:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${ipServer}:${porteureka}/eureka/
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msproduits:
    image: epitech/produits:${versionMsProduits}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${ipServer}:${porteureka}/eureka/
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  mscommandes:
    image: epitech/commandes:${versionMsCommandes}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${ipServer}:${porteureka}/eureka/
      - spring_activemq_broker_url=tcp://${ipServer}:${activeMqbroker}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msnotifications:
    image: epitech/notifications:${versionMsNotifications}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${ipServer}:${porteureka}/eureka/
      - spring_activemq_broker_url=tcp://${ipServer}:${activeMqbroker}
      - spring_mail_host=${ipServer}
      - spring_mail_port=${mailhogSmtpPort}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  messagebroker:
    image: rmohr/activemq:5.10.0
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
    ports:
      - ${activeMqbroker}:61616
      - ${activeMqweb}:8161
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 200MB
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - ${mailhogSmtpPort}:1025 # smtp server
      - ${mailhogWebPort}:8025 # web ui
    volumes:
      - ./auth.file:/data/mailhog/auth.file
    entrypoint: MailHog -auth-file=/data/mailhog/auth.file
    environment:
      MH_STORAGE: memory
    deploy:
      resources:
        limits:
          memory: 1G
