version: "3.3"
services:
  gateway:
    image: epitech/gateway:latest
    container_name: epitech-gateway-${env}
    environment:
      - BLA=bla
    restart: on-failure:5
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
