version: "3.3"
services:
  eureka:
    image: epitech/eureka:latest
    container_name: epitech-eureka-${env}
    environment:
      - BLA=bla
    restart: on-failure:5
    ports:
      - ${porteureka}:8761
    networks:
      - internal-epitech
    deploy:
      resources:
        limits:
          memory: 200MB
  gateway:
    image: epitech/gateway:latest
    container_name: epitech-gateway-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://10.0.40.18:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msproduits:
    image: epitech/produits:latest
    container_name: epitech-produits-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://10.0.40.18:${porteureka}/eureka/
    restart: on-failure:5
    ports:
      - ${portgateway}:8762
    networks:
      - internal-epitech
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  mscommandes:
    image: epitech/commandes:latest
    container_name: epitech-commandes-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://10.0.40.18:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msnotifications:
    image: epitech/notifications:latest
    container_name: epitech-notifications-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://10.0.40.18:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
networks:
  internal-epitech:
    driver: overlay
