version: "3.3"
services:
  eureka:
    image: epitech/eureka:latest
    container_name: epitech-eureka-${env}
    environment:
      - BLA=bla
    restart: on-failure:5
    ports:
      - ${porteureka}:8761
    networks:
      - internal-epitech
    deploy:
      resources:
        limits:
          memory: 200MB
  gateway:
    image: epitech/gateway:latest
    container_name: epitech-gateway-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${ipServer}:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msproduits:
    image: epitech/produits:${versionMsProduits}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${ipServer}:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  mscommandes:
    image: epitech/commandes:${versionMsCommandes}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${ipServer}:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
  msnotifications:
    image: epitech/notifications:${versionMsNotifications}
    environment:
      - eureka_client_serviceUrl_defaultZone=http://${ipServer}:${porteureka}/eureka/
    restart: on-failure:5
    networks:
      - internal-epitech
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
networks:
  internal-epitech:
    driver: bridge
    #name: epitech-network-${env}
