version: "3.3"
services:
  eureka:
    image: epitech/eureka:latest
    container_name: epitech-eureka-${env}
    environment:
      - BLA=bla
    restart: on-failure:5
    ports:
      - ${porteureka}:8761
    deploy:
      resources:
        limits:
          memory: 200MB
  gateway:
    image: epitech/gateway:latest
    container_name: epitech-gateway-${env}
    environment:
      - eureka_client_serviceUrl_defaultZone=https://workshop-epitech.iaas.ippon.fr:${porteureka}/eureka/
    restart: on-failure:5
    ports:
      - ${portgateway}:8762
    deploy:
      resources:
        limits:
          memory: 200MB
    depends_on:
      - eureka
